### ISSUE TITLE
dont-work

### ISSUE THREAD

**Issue by Golden-Puma** [bas2k/jquery.appear#8]
dont work with jQuery v3.4.1 

jquery.min.js:2 Uncaught TypeError: $(...).appear is not a function
    at HTMLDocument.<anonymous> (script.js:386)
    at e (jquery.min.js:2)
    at t (jquery.min.js:2)
